name = "juntohyo-server"
main = "dist/index.js"
compatibility_date = "2025-10-14"
preview_urls = false

[build]
command = "bun build --outdir=dist --target=browser --minify ./src/index.ts"

[dev]
port = 8787
